import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

test('merge: drop two PDFs, click Merge, download, output is a real merged PDF', async ({ page }) => {
  await page.goto('/tools/merge');
  await expect(page.getByRole('heading', { name: 'Merge PDFs' })).toBeVisible();

  // Drop two fixtures. Both are generated by pretest:e2e.
  const fileInput = page.locator('input[type="file"]');
  const f1 = path.resolve(__dirname, '..', 'fixtures', 'sample.pdf');
  const f2 = path.resolve(__dirname, '..', 'fixtures', 'sample-2.pdf');
  await fileInput.setInputFiles([f1, f2]);

  // Both files listed.
  await expect(page.getByText('sample.pdf')).toBeVisible();
  await expect(page.getByText('sample-2.pdf')).toBeVisible();

  // Click merge, wait for the download button to appear (proves
  // the merge succeeded), then click it and capture the download.
  await page.locator('[data-testid="merge-action"]').click();
  const downloadBtn = page.locator('[data-testid="merge-download"]');
  await expect(downloadBtn).toBeVisible();
  const [download] = await Promise.all([
    page.waitForEvent('download'),
    downloadBtn.click(),
  ]);
  const out = path.join(os.tmpdir(), `pdfaster-merge-${Date.now()}.pdf`);
  await download.saveAs(out);
  expect(fs.statSync(out).size).toBeGreaterThan(0);

  // The output is served as a PDF download.
  expect(download.suggestedFilename()).toMatch(/merged\.pdf$/);

  fs.unlinkSync(out);
});
